### ISSUE TITLE
Codes of reproducing baseline results

### ISSUE THREAD

**Issue by qsong2001** [albblgb/PUSNet#1]
Dear author,

Your brilliant idea in ``PUSNet'' is impressive. : )

Thanks for releasing codes and pre-trained models.

Currently, I am reproducing some experimental results in your paper (baluja, hiden, etal.). 
However,  I noticed that there are only weight files available, without the accompanying model class (.py) that can load these pretrained weights (**model**.load_state_dict(ckpt)).  I couldn't find the proper models on GitHub.

Would you kindly release the  .py file that can load these weights? 

Thank you!

**Comment by qsong2001** [comment]
I just noted your projects [Hiding-images-within-images](https://github.com/albblgb/Hiding-images-within-images).
Wishing you more acceptance. 💯

**Comment by albblgb** [comment]
hahah.
